### ISSUE TITLE
Stops within a track are not respected while producing TCX

### ISSUE THREAD

**Issue by hadeone** [mlt/schwinn810#8] opened 2012-06-07 15:15 UTC
I had a weird occurrence yesterday : When I imported my data I noticed only half of my ride was in the tcx file, even though the .points file shows my actual last location. During my ride I did stop a few times and I hit stop (without saving the data) then I re-started (new lap) and eventually saved the data at the end of the whole ride. I;m guessing that this created a situation that csv2tcx didn't like because it only converted my ride up until my stop. 

Any idea if I can get csv2tcx to use only the .points file, without the .lap file? I'm not even sure if there is data missing from the lap file because trainingpeaks shows 8 laps while the watch says it recorded 14 laps. 

Any insight would be appreciated. 

Otherwise everything works great. Last time I stopped I saved the data then I was able to combine the 2 tcx files I created on one run. I will do this from now on to avoid errors like this.

**Comment by mlt** [comment] 2012-06-07 15:47
I remember I didn't like how I cut points using laps data. I guess this is a consequence:)

Could you zip all 3 files for your track and use sendspace, Dropbox or something if you don't mind sharing where you've been. It would help me debug.

You can use gpsbabel if you are not interested in splits. I don't remember what it does with the heart rate though. You can look in commit history of babelize.cmd to see traces of gpsbabel use for TCX. 

Mikhail

**Comment by hadeone** [comment] 2012-06-07 16:39
I tried using the GPSBABEL gui for windows but it didn't want to convert just the .points file to tcx. I'm probably not using it right but will keep trying. 

Can I email you the files / link or does githib have a private message feature? I couldn't find one.

Thanks

**Comment by mlt** [comment] 2012-06-07 16:53
I never used gpsbabel GUI. Try telling it that points are in unicsv format.

**Comment by mlt** [comment] 2012-06-12 00:27
The issue is caused by the absence of absolute time in laps returned by watch thus making it cumbersome to split GPS data points.

Here is the [workaround](https://github.com/mlt/schwinn810/blob/master/src/babelize.cmd#L7) if you don't care about track splits

``` bat
gpsbabel.exe -i unicsv,utc=4 -f 0606101.points -x transform,trk=wpt -o gtrnctr,course=0 -F 0606101.tcx
```

If you are using GPSBabel FE, make sure to tick conversion from waypoints to track and make sure you somehow export activity (?) and not the course.

**Comment by hadeone** [comment] 2012-06-14 12:56
GPSBabel omits the speed data so I'll work around the issue by saving the data any time I take a long break along a route. The resulting TCX files can then be joined together and all of the data will be intact. 

Thanks for your help once again!

**Comment by mlt** [comment] 2012-06-14 21:30
> saving the data any time I take a long break along a route

That is not a solution but a workaround. If TCX I sent you appear okay, I'll commit changes that probably will make splitting more reliable even when stops are present.

> GPSBabel omits the speed data

Mine TCX converter also does not insert speed at each point. Only maximum speed. I'll see it it is a matter of improperly named column for _unicsv_ format.

**Comment by nc54** [comment] 2012-06-26 20:54
Checked out the new fix. Works for me. This time I stopped without hitting the stop button for 9 minutes, the old version cut off 1.5 minutes the new one did not.

**Comment by mlt** [comment] 2012-07-02 16:27
It should be no problem for single lap tracks. All problems begin when we want to cut track points by laps. It is tricky especially when it comes to erroneous press on _new lap_. The lap will have a start time of the next lap, If there are no points recorded for a given lap. But who cares? :-)

I'm closing this one. Reopen if this issue persists.

**Closed as completed by mlt** 2012-07-02 16:27 UTC
