### ISSUE TITLE
Tracks cut short

### ISSUE THREAD

**Issue by nc54** [mlt/schwinn810#11] opened 2012-06-23 23:32 UTC
Tracks downloaded are incomplete when compared to tracks downloaded from OEM Software. The ride ends a mile or two early.
I have only had one track that I know of that has had this problem.  
from OEM software download:  https://dl.dropbox.com/u/19832238/Complete.TCX
From Here: https://dl.dropbox.com/u/19832238/incomplete.TCX

FYI, This track showed incorrect before and after the elevation fix so that change is unrelated.

Here is the debug: https://dl.dropbox.com/u/19832238/schwinn810Incomplete.bin

**Comment by mlt** [comment] 2012-06-24 01:12
> I have only had one track that I know of that has had this problem.

That is quite an odd track.

I still don't know how watch measures track/lap time. By looking at start/end time of your track, it looks like it should last ~8704 seconds. However when you look at your laps (you have 1), it says that your lap time is 8005.78 seconds (it also reports 8009 in another field but I don't understand quite the difference between two fields). So there is huge deviation between dot track (or actually dot points as dot track does not report seconds of track end) and dot laps file.

Furthermore by looking at time gap histogram and various plots, I see that you've made stops, e.g. one around 11:39:10 till 11:44:30. This leads me to believe that your issue is a duplicate of #8

You can use R to plot those yourself.

``` R
x <- read.csv("0623102.points",colClasses=c(Time="POSIXct"))
q <- as.double(diff(x$Time),units="secs")
hist(q[q>4])
plot(x$Speed~q)
w <- diff(x$Distance)
plot(w/q~q)
which.min(q>300)
x[2298:2300,]
```

> This track showed incorrect before and after the elevation fix so that change is unrelated

So that is not quite true as I've tried to fix both issues in the last release at once. Apparently I did not succeed at it.

It looks like that watch is "smart" no to count stop time towards lap time. Which leaves the only option to split tracks by lap, i.e. distance and autolap flag.

I'm closing it as a duplicate. Please follow #8.

**Closed as completed by mlt** 2012-06-24 01:12 UTC
Labels: duplicate

**Comment by nc54** [comment] 2012-06-24 01:39
Yes I did stop the timer.. twice, maybe three times.  I do believe this is a duplicate.

**Comment by mlt** [comment] 2012-06-25 00:40
While you did stop, I'm not that positive that you did stop the timer. In that case you would start a new lap once you continue and there is only one lap in that track.

**Comment by nc54** [comment] 2012-06-25 00:54
I hit the lower right "stop"  button.  Then used the upper right
"lap/start" button to start.  This does not create a lap, but pauses the
timer.  I wonder if the missing segment time = stop time.
On Jun 24, 2012 6:40 PM, "Mikhail Titov" <
reply@reply.github.com>
wrote:

**Comment by mlt** [comment] 2012-06-25 23:52
> I hit the lower right "stop"  button.  Then used the upper right
> "lap/start" button to start.  This does not create a lap, but pauses the
> timer.

For some reason I always thought it does start a new lap. Good to know.

> I wonder if the missing segment time = stop time.

Probably but it needs to be checked. Also it looks like most of the online site re-calculate lap time based on GPS data, thus rendering accurate lap time useless.
